// <auto-generated />
using ItlaTaks.Infraestructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ItlaTaks.Infraestructure.Migrations
{
    [DbContext(typeof(TaskContext))]
    [Migration("20251025175721_terceramigracion")]
    partial class terceramigracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ItlaTaks.Infraestructure.Models.MateriaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Creditos")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("ItlaTaks.Infraestructure.Models.ProfesorMateriaModel", b =>
                {
                    b.Property<int>("IdProfesor")
                        .HasColumnType("int");

                    b.Property<int>("MateriaId")
                        .HasColumnType("int");

                    b.HasKey("IdProfesor", "MateriaId");

                    b.HasIndex("MateriaId");

                    b.ToTable("ProfesorMaterias");
                });

            modelBuilder.Entity("ItlaTaks.Infraestructure.Models.ProfesorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Profesores");
                });

            modelBuilder.Entity("ItlaTaks.Infraestructure.Models.ProfesorMateriaModel", b =>
                {
                    b.HasOne("ItlaTaks.Infraestructure.Models.ProfesorModel", "Profesor")
                        .WithMany("ProfesorMaterias")
                        .HasForeignKey("IdProfesor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ItlaTaks.Infraestructure.Models.MateriaModel", "Materia")
                        .WithMany("ProfesorMaterias")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Materia");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("ItlaTaks.Infraestructure.Models.MateriaModel", b =>
                {
                    b.Navigation("ProfesorMaterias");
                });

            modelBuilder.Entity("ItlaTaks.Infraestructure.Models.ProfesorModel", b =>
                {
                    b.Navigation("ProfesorMaterias");
                });
#pragma warning restore 612, 618
        }
    }
}
